version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@3.0.1

workflows:
  test_and_deploy_on_heroku:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test
          filters:
            branches:
              only: master
